stages:
- "test"

.test-template:
  stage: test
  image: python:3.9.6-slim-buster
  tags:
  - kubernetes-runner
  - docker-runner
  except:
  - tags
  before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

black:
  extends:
  - .test-template
  script:
  - black --check .

pytest:
  extends:
  - .test-template
  script:
  - pytest -vv --junitxml=report.xml --cov="dr_transcribe" .
  - coverage xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
